name: RECODE WEEKLY 자동 생성 및 발송

on:
  schedule:
    # 매주 금요일 새벽 0시 (KST) = 목요일 15:00 UTC
    - cron: '0 15 * * 4'
  
  # 수동 실행 가능
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v3
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 의존성 설치
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install pandas
    
    - name: 보고서 생성
      run: |
        python scripts/generate_report.py
        echo "보고서 생성 완료"
    
    - name: 생성된 보고서 파일 찾기
      id: find-report
      run: |
        REPORT_FILE=$(ls reports/recode_weekly_*.html | head -1)
        echo "report_path=$REPORT_FILE" >> $GITHUB_OUTPUT
        echo "보고서 파일: $REPORT_FILE"
    
    - name: 이메일 발송
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_NAME: "RECODE WEEKLY"
      run: |
        python scripts/send_email.py "${{ steps.find-report.outputs.report_path }}"
    
    - name: GitHub Pages에 배포
      if: success()
      run: |
        # GitHub Pages 브랜치로 보고서 복사
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # gh-pages 브랜치가 없으면 생성
        git checkout gh-pages 2>/dev/null || git checkout -b gh-pages
        
        # 최신 보고서 복사
        cp "${{ steps.find-report.outputs.report_path }}" ./index.html
        
        # 아카이브 디렉토리에도 저장
        mkdir -p archive
        cp "${{ steps.find-report.outputs.report_path }}" ./archive/
        
        # 커밋 및 푸시
        git add .
        git commit -m "Update RECODE WEEKLY - $(date +'%Y.%m.%d')"
        git push origin gh-pages
    
    - name: 실행 로그 저장
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs
        path: |
          reports/
          *.log